// Astryx semantic token contract — Figma "OOP 디자인 토큰" 컬렉션 01-05 (133개 고유 변수).
// Figma export와 이름·값 100% 일치 (2026-07-31 수신; 원본은 레포 밖 보관).
// color.border.base(→ --color-border)만 Figma export에 없으나 Astryx에 존재하는 기본 border
// 토큰으로, 앱에서 실제 사용하므로 contract에 추가했다 (AGENTS.md: Astryx에 존재하는 이름만 추가).
// 값은 Astryx(@astryxdesign/core)가 런타임에 :root로 공급하므로 여기서 다시 선언하지 않는다.
// createGlobalThemeContract는 CSS를 emit하지 않고, 접근 시 var(--...) 문자열을 반환한다.
import { createGlobalThemeContract } from '@vanilla-extract/css';

export const tokens = createGlobalThemeContract({
  spacing: {
    '0': 'spacing-0',
    '1': 'spacing-1',
    '2': 'spacing-2',
    '3': 'spacing-3',
    '4': 'spacing-4',
    '5': 'spacing-5',
    '6': 'spacing-6',
    '7': 'spacing-7',
    '8': 'spacing-8',
    '9': 'spacing-9',
    '10': 'spacing-10',
    '11': 'spacing-11',
    '12': 'spacing-12',
    '0-5': 'spacing-0-5',
    '1-5': 'spacing-1-5',
  },
  size: {
    'element-sm': 'size-element-sm',
    'element-md': 'size-element-md',
    'element-lg': 'size-element-lg',
  },
  'border-width': 'border-width',
  radius: {
    none: 'radius-none',
    inner: 'radius-inner',
    element: 'radius-element',
    container: 'radius-container',
    page: 'radius-page',
    chat: 'radius-chat',
    full: 'radius-full',
  },
  color: {
    accent: 'color-accent',
    'accent-muted': 'color-accent-muted',
    'on-accent': 'color-on-accent',
    neutral: 'color-neutral',
    overlay: 'color-overlay',
    'overlay-hover': 'color-overlay-hover',
    'overlay-pressed': 'color-overlay-pressed',
    'on-dark': 'color-on-dark',
    'on-light': 'color-on-light',
    success: 'color-success',
    'success-muted': 'color-success-muted',
    'on-success': 'color-on-success',
    error: 'color-error',
    'error-muted': 'color-error-muted',
    'on-error': 'color-on-error',
    warning: 'color-warning',
    'warning-muted': 'color-warning-muted',
    'on-warning': 'color-on-warning',
    'border-emphasized': 'color-border-emphasized',
    skeleton: 'color-skeleton',
    track: 'color-track',
    shadow: 'color-shadow',
    'tint-hover': 'color-tint-hover',
    background: {
      surface: 'color-background-surface',
      body: 'color-background-body',
      muted: 'color-background-muted',
      card: 'color-background-card',
      popover: 'color-background-popover',
      inverted: 'color-background-inverted',
      'error-inverted': 'color-background-error-inverted',
      blue: 'color-background-blue',
      cyan: 'color-background-cyan',
      gray: 'color-background-gray',
      green: 'color-background-green',
      orange: 'color-background-orange',
      pink: 'color-background-pink',
      purple: 'color-background-purple',
      red: 'color-background-red',
      teal: 'color-background-teal',
      yellow: 'color-background-yellow',
    },
    text: {
      primary: 'color-text-primary',
      secondary: 'color-text-secondary',
      disabled: 'color-text-disabled',
      accent: 'color-text-accent',
      blue: 'color-text-blue',
      cyan: 'color-text-cyan',
      gray: 'color-text-gray',
      green: 'color-text-green',
      orange: 'color-text-orange',
      pink: 'color-text-pink',
      purple: 'color-text-purple',
      red: 'color-text-red',
      teal: 'color-text-teal',
      yellow: 'color-text-yellow',
    },
    icon: {
      accent: 'color-icon-accent',
      primary: 'color-icon-primary',
      secondary: 'color-icon-secondary',
      disabled: 'color-icon-disabled',
      blue: 'color-icon-blue',
      cyan: 'color-icon-cyan',
      gray: 'color-icon-gray',
      green: 'color-icon-green',
      orange: 'color-icon-orange',
      pink: 'color-icon-pink',
      purple: 'color-icon-purple',
      red: 'color-icon-red',
      teal: 'color-icon-teal',
      yellow: 'color-icon-yellow',
    },
    border: {
      base: 'color-border',
      blue: 'color-border-blue',
      cyan: 'color-border-cyan',
      gray: 'color-border-gray',
      green: 'color-border-green',
      orange: 'color-border-orange',
      pink: 'color-border-pink',
      purple: 'color-border-purple',
      red: 'color-border-red',
      teal: 'color-border-teal',
      yellow: 'color-border-yellow',
    },
  },
  duration: {
    'fast-min': 'duration-fast-min',
    fast: 'duration-fast',
    'fast-max': 'duration-fast-max',
    'medium-min': 'duration-medium-min',
    medium: 'duration-medium',
    'medium-max': 'duration-medium-max',
    'slow-min': 'duration-slow-min',
    slow: 'duration-slow',
    'slow-max': 'duration-slow-max',
  },
  ease: {
    standard: 'ease-standard',
  },
  'font-size': {
    '4xs': 'font-size-4xs',
    '3xs': 'font-size-3xs',
    '2xs': 'font-size-2xs',
    xs: 'font-size-xs',
    sm: 'font-size-sm',
    base: 'font-size-base',
    lg: 'font-size-lg',
    xl: 'font-size-xl',
    '2xl': 'font-size-2xl',
    '3xl': 'font-size-3xl',
    '4xl': 'font-size-4xl',
    '5xl': 'font-size-5xl',
  },
  'font-weight': {
    normal: 'font-weight-normal',
    medium: 'font-weight-medium',
    semibold: 'font-weight-semibold',
    bold: 'font-weight-bold',
  },
  'font-family': {
    body: 'font-family-body',
    heading: 'font-family-heading',
    code: 'font-family-code',
  },
});
