/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const StudentLazyRouteImport = createFileRoute('/student')()
const LoginLazyRouteImport = createFileRoute('/login')()
const AdminLazyRouteImport = createFileRoute('/admin')()
const IndexLazyRouteImport = createFileRoute('/')()
const StudentIndexLazyRouteImport = createFileRoute('/student/')()
const AdminIndexLazyRouteImport = createFileRoute('/admin/')()
const StudentTeamLazyRouteImport = createFileRoute('/student/team')()
const StudentProjectTopicLazyRouteImport = createFileRoute(
  '/student/project-topic',
)()
const StudentPresentationEvaluationLazyRouteImport = createFileRoute(
  '/student/presentation-evaluation',
)()
const StudentPeerReviewLazyRouteImport = createFileRoute(
  '/student/peer-review',
)()
const StudentNoticesLazyRouteImport = createFileRoute('/student/notices')()
const StudentMeetingsLazyRouteImport = createFileRoute('/student/meetings')()
const StudentGradesLazyRouteImport = createFileRoute('/student/grades')()
const StudentFeedbackLazyRouteImport = createFileRoute('/student/feedback')()
const OnboardingTeamLazyRouteImport = createFileRoute('/onboarding/team')()
const AdminSubmissionsLazyRouteImport = createFileRoute('/admin/submissions')()
const AdminStudentTeamLazyRouteImport = createFileRoute('/admin/student-team')()
const AdminProfileLazyRouteImport = createFileRoute('/admin/profile')()
const AdminNoticesLazyRouteImport = createFileRoute('/admin/notices')()
const AdminMeetingsLazyRouteImport = createFileRoute('/admin/meetings')()
const StudentNoticesIndexLazyRouteImport =
  createFileRoute('/student/notices/')()
const StudentMeetingsIndexLazyRouteImport =
  createFileRoute('/student/meetings/')()
const OnboardingTeamIndexLazyRouteImport =
  createFileRoute('/onboarding/team/')()
const AdminSubmissionsIndexLazyRouteImport = createFileRoute(
  '/admin/submissions/',
)()
const AdminNoticesIndexLazyRouteImport = createFileRoute('/admin/notices/')()
const AdminMilestonesIndexLazyRouteImport =
  createFileRoute('/admin/milestones/')()
const AdminMeetingsIndexLazyRouteImport = createFileRoute('/admin/meetings/')()
const StudentNoticesNoticeIdLazyRouteImport = createFileRoute(
  '/student/notices/$noticeId',
)()
const StudentMeetingsNewLazyRouteImport = createFileRoute(
  '/student/meetings/new',
)()
const StudentMeetingsMeetingIdLazyRouteImport = createFileRoute(
  '/student/meetings/$meetingId',
)()
const OnboardingTeamSurveyLazyRouteImport = createFileRoute(
  '/onboarding/team/survey',
)()
const OnboardingTeamResultLazyRouteImport = createFileRoute(
  '/onboarding/team/result',
)()
const OnboardingTeamFirstMeetingLazyRouteImport = createFileRoute(
  '/onboarding/team/first-meeting',
)()
const AdminTeamsTeamIdLazyRouteImport = createFileRoute(
  '/admin/teams/$teamId',
)()
const AdminSubmissionsSubmissionIdLazyRouteImport = createFileRoute(
  '/admin/submissions/$submissionId',
)()
const AdminNoticesNewLazyRouteImport = createFileRoute('/admin/notices/new')()
const AdminNoticesNoticeIdLazyRouteImport = createFileRoute(
  '/admin/notices/$noticeId',
)()
const AdminMilestonesNewLazyRouteImport = createFileRoute(
  '/admin/milestones/new',
)()
const AdminMeetingsMeetingIdLazyRouteImport = createFileRoute(
  '/admin/meetings/$meetingId',
)()
const StudentNoticesNoticeIdIndexLazyRouteImport = createFileRoute(
  '/student/notices/$noticeId/',
)()
const StudentMeetingsMeetingIdIndexLazyRouteImport = createFileRoute(
  '/student/meetings/$meetingId/',
)()
const AdminNoticesNoticeIdIndexLazyRouteImport = createFileRoute(
  '/admin/notices/$noticeId/',
)()
const StudentMeetingsMeetingIdEditLazyRouteImport = createFileRoute(
  '/student/meetings/$meetingId/edit',
)()
const StudentEditorProposalSectionLazyRouteImport = createFileRoute(
  '/student/editor/proposal/$section',
)()
const StudentEditorPresentationSectionLazyRouteImport = createFileRoute(
  '/student/editor/presentation/$section',
)()
const StudentEditorMidReviewSectionLazyRouteImport = createFileRoute(
  '/student/editor/mid-review/$section',
)()
const AdminNoticesNoticeIdEditLazyRouteImport = createFileRoute(
  '/admin/notices/$noticeId/edit',
)()

const StudentLazyRoute = StudentLazyRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/student.lazy').then((d) => d.Route))
const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const AdminLazyRoute = AdminLazyRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const StudentIndexLazyRoute = StudentIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentLazyRoute,
} as any).lazy(() => import('./routes/student.index.lazy').then((d) => d.Route))
const AdminIndexLazyRoute = AdminIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLazyRoute,
} as any).lazy(() => import('./routes/admin.index.lazy').then((d) => d.Route))
const StudentTeamLazyRoute = StudentTeamLazyRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => StudentLazyRoute,
} as any).lazy(() => import('./routes/student.team.lazy').then((d) => d.Route))
const StudentProjectTopicLazyRoute = StudentProjectTopicLazyRouteImport.update({
  id: '/project-topic',
  path: '/project-topic',
  getParentRoute: () => StudentLazyRoute,
} as any).lazy(() =>
  import('./routes/student.project-topic.lazy').then((d) => d.Route),
)
const StudentPresentationEvaluationLazyRoute =
  StudentPresentationEvaluationLazyRouteImport.update({
    id: '/presentation-evaluation',
    path: '/presentation-evaluation',
    getParentRoute: () => StudentLazyRoute,
  } as any).lazy(() =>
    import('./routes/student.presentation-evaluation.lazy').then(
      (d) => d.Route,
    ),
  )
const StudentPeerReviewLazyRoute = StudentPeerReviewLazyRouteImport.update({
  id: '/peer-review',
  path: '/peer-review',
  getParentRoute: () => StudentLazyRoute,
} as any).lazy(() =>
  import('./routes/student.peer-review.lazy').then((d) => d.Route),
)
const StudentNoticesLazyRoute = StudentNoticesLazyRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => StudentLazyRoute,
} as any).lazy(() =>
  import('./routes/student.notices.lazy').then((d) => d.Route),
)
const StudentMeetingsLazyRoute = StudentMeetingsLazyRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => StudentLazyRoute,
} as any).lazy(() =>
  import('./routes/student.meetings.lazy').then((d) => d.Route),
)
const StudentGradesLazyRoute = StudentGradesLazyRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => StudentLazyRoute,
} as any).lazy(() =>
  import('./routes/student.grades.lazy').then((d) => d.Route),
)
const StudentFeedbackLazyRoute = StudentFeedbackLazyRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => StudentLazyRoute,
} as any).lazy(() =>
  import('./routes/student.feedback.lazy').then((d) => d.Route),
)
const OnboardingTeamLazyRoute = OnboardingTeamLazyRouteImport.update({
  id: '/onboarding/team',
  path: '/onboarding/team',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/onboarding.team.lazy').then((d) => d.Route),
)
const AdminSubmissionsLazyRoute = AdminSubmissionsLazyRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminLazyRoute,
} as any).lazy(() =>
  import('./routes/admin.submissions.lazy').then((d) => d.Route),
)
const AdminStudentTeamLazyRoute = AdminStudentTeamLazyRouteImport.update({
  id: '/student-team',
  path: '/student-team',
  getParentRoute: () => AdminLazyRoute,
} as any).lazy(() =>
  import('./routes/admin.student-team.lazy').then((d) => d.Route),
)
const AdminProfileLazyRoute = AdminProfileLazyRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminLazyRoute,
} as any).lazy(() => import('./routes/admin.profile.lazy').then((d) => d.Route))
const AdminNoticesLazyRoute = AdminNoticesLazyRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AdminLazyRoute,
} as any).lazy(() => import('./routes/admin.notices.lazy').then((d) => d.Route))
const AdminMeetingsLazyRoute = AdminMeetingsLazyRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AdminLazyRoute,
} as any).lazy(() =>
  import('./routes/admin.meetings.lazy').then((d) => d.Route),
)
const StudentNoticesIndexLazyRoute = StudentNoticesIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentNoticesLazyRoute,
} as any).lazy(() =>
  import('./routes/student.notices.index.lazy').then((d) => d.Route),
)
const StudentMeetingsIndexLazyRoute =
  StudentMeetingsIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StudentMeetingsLazyRoute,
  } as any).lazy(() =>
    import('./routes/student.meetings.index.lazy').then((d) => d.Route),
  )
const OnboardingTeamIndexLazyRoute = OnboardingTeamIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingTeamLazyRoute,
} as any).lazy(() =>
  import('./routes/onboarding.team.index.lazy').then((d) => d.Route),
)
const AdminSubmissionsIndexLazyRoute =
  AdminSubmissionsIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminSubmissionsLazyRoute,
  } as any).lazy(() =>
    import('./routes/admin.submissions.index.lazy').then((d) => d.Route),
  )
const AdminNoticesIndexLazyRoute = AdminNoticesIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminNoticesLazyRoute,
} as any).lazy(() =>
  import('./routes/admin.notices.index.lazy').then((d) => d.Route),
)
const AdminMilestonesIndexLazyRoute =
  AdminMilestonesIndexLazyRouteImport.update({
    id: '/milestones/',
    path: '/milestones/',
    getParentRoute: () => AdminLazyRoute,
  } as any).lazy(() =>
    import('./routes/admin.milestones.index.lazy').then((d) => d.Route),
  )
const AdminMeetingsIndexLazyRoute = AdminMeetingsIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminMeetingsLazyRoute,
} as any).lazy(() =>
  import('./routes/admin.meetings.index.lazy').then((d) => d.Route),
)
const StudentNoticesNoticeIdLazyRoute =
  StudentNoticesNoticeIdLazyRouteImport.update({
    id: '/$noticeId',
    path: '/$noticeId',
    getParentRoute: () => StudentNoticesLazyRoute,
  } as any).lazy(() =>
    import('./routes/student.notices.$noticeId.lazy').then((d) => d.Route),
  )
const StudentMeetingsNewLazyRoute = StudentMeetingsNewLazyRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => StudentMeetingsLazyRoute,
} as any).lazy(() =>
  import('./routes/student.meetings.new.lazy').then((d) => d.Route),
)
const StudentMeetingsMeetingIdLazyRoute =
  StudentMeetingsMeetingIdLazyRouteImport.update({
    id: '/$meetingId',
    path: '/$meetingId',
    getParentRoute: () => StudentMeetingsLazyRoute,
  } as any).lazy(() =>
    import('./routes/student.meetings.$meetingId.lazy').then((d) => d.Route),
  )
const OnboardingTeamSurveyLazyRoute =
  OnboardingTeamSurveyLazyRouteImport.update({
    id: '/survey',
    path: '/survey',
    getParentRoute: () => OnboardingTeamLazyRoute,
  } as any).lazy(() =>
    import('./routes/onboarding.team.survey.lazy').then((d) => d.Route),
  )
const OnboardingTeamResultLazyRoute =
  OnboardingTeamResultLazyRouteImport.update({
    id: '/result',
    path: '/result',
    getParentRoute: () => OnboardingTeamLazyRoute,
  } as any).lazy(() =>
    import('./routes/onboarding.team.result.lazy').then((d) => d.Route),
  )
const OnboardingTeamFirstMeetingLazyRoute =
  OnboardingTeamFirstMeetingLazyRouteImport.update({
    id: '/first-meeting',
    path: '/first-meeting',
    getParentRoute: () => OnboardingTeamLazyRoute,
  } as any).lazy(() =>
    import('./routes/onboarding.team.first-meeting.lazy').then((d) => d.Route),
  )
const AdminTeamsTeamIdLazyRoute = AdminTeamsTeamIdLazyRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => AdminLazyRoute,
} as any).lazy(() =>
  import('./routes/admin.teams.$teamId.lazy').then((d) => d.Route),
)
const AdminSubmissionsSubmissionIdLazyRoute =
  AdminSubmissionsSubmissionIdLazyRouteImport.update({
    id: '/$submissionId',
    path: '/$submissionId',
    getParentRoute: () => AdminSubmissionsLazyRoute,
  } as any).lazy(() =>
    import('./routes/admin.submissions.$submissionId.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminNoticesNewLazyRoute = AdminNoticesNewLazyRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminNoticesLazyRoute,
} as any).lazy(() =>
  import('./routes/admin.notices.new.lazy').then((d) => d.Route),
)
const AdminNoticesNoticeIdLazyRoute =
  AdminNoticesNoticeIdLazyRouteImport.update({
    id: '/$noticeId',
    path: '/$noticeId',
    getParentRoute: () => AdminNoticesLazyRoute,
  } as any).lazy(() =>
    import('./routes/admin.notices.$noticeId.lazy').then((d) => d.Route),
  )
const AdminMilestonesNewLazyRoute = AdminMilestonesNewLazyRouteImport.update({
  id: '/milestones/new',
  path: '/milestones/new',
  getParentRoute: () => AdminLazyRoute,
} as any).lazy(() =>
  import('./routes/admin.milestones.new.lazy').then((d) => d.Route),
)
const AdminMeetingsMeetingIdLazyRoute =
  AdminMeetingsMeetingIdLazyRouteImport.update({
    id: '/$meetingId',
    path: '/$meetingId',
    getParentRoute: () => AdminMeetingsLazyRoute,
  } as any).lazy(() =>
    import('./routes/admin.meetings.$meetingId.lazy').then((d) => d.Route),
  )
const StudentNoticesNoticeIdIndexLazyRoute =
  StudentNoticesNoticeIdIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StudentNoticesNoticeIdLazyRoute,
  } as any).lazy(() =>
    import('./routes/student.notices.$noticeId.index.lazy').then(
      (d) => d.Route,
    ),
  )
const StudentMeetingsMeetingIdIndexLazyRoute =
  StudentMeetingsMeetingIdIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StudentMeetingsMeetingIdLazyRoute,
  } as any).lazy(() =>
    import('./routes/student.meetings.$meetingId.index.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminNoticesNoticeIdIndexLazyRoute =
  AdminNoticesNoticeIdIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminNoticesNoticeIdLazyRoute,
  } as any).lazy(() =>
    import('./routes/admin.notices.$noticeId.index.lazy').then((d) => d.Route),
  )
const StudentMeetingsMeetingIdEditLazyRoute =
  StudentMeetingsMeetingIdEditLazyRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => StudentMeetingsMeetingIdLazyRoute,
  } as any).lazy(() =>
    import('./routes/student.meetings.$meetingId.edit.lazy').then(
      (d) => d.Route,
    ),
  )
const StudentEditorProposalSectionLazyRoute =
  StudentEditorProposalSectionLazyRouteImport.update({
    id: '/editor/proposal/$section',
    path: '/editor/proposal/$section',
    getParentRoute: () => StudentLazyRoute,
  } as any).lazy(() =>
    import('./routes/student.editor.proposal.$section.lazy').then(
      (d) => d.Route,
    ),
  )
const StudentEditorPresentationSectionLazyRoute =
  StudentEditorPresentationSectionLazyRouteImport.update({
    id: '/editor/presentation/$section',
    path: '/editor/presentation/$section',
    getParentRoute: () => StudentLazyRoute,
  } as any).lazy(() =>
    import('./routes/student.editor.presentation.$section.lazy').then(
      (d) => d.Route,
    ),
  )
const StudentEditorMidReviewSectionLazyRoute =
  StudentEditorMidReviewSectionLazyRouteImport.update({
    id: '/editor/mid-review/$section',
    path: '/editor/mid-review/$section',
    getParentRoute: () => StudentLazyRoute,
  } as any).lazy(() =>
    import('./routes/student.editor.mid-review.$section.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminNoticesNoticeIdEditLazyRoute =
  AdminNoticesNoticeIdEditLazyRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AdminNoticesNoticeIdLazyRoute,
  } as any).lazy(() =>
    import('./routes/admin.notices.$noticeId.edit.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/admin': typeof AdminLazyRouteWithChildren
  '/login': typeof LoginLazyRoute
  '/student': typeof StudentLazyRouteWithChildren
  '/admin/meetings': typeof AdminMeetingsLazyRouteWithChildren
  '/admin/notices': typeof AdminNoticesLazyRouteWithChildren
  '/admin/profile': typeof AdminProfileLazyRoute
  '/admin/student-team': typeof AdminStudentTeamLazyRoute
  '/admin/submissions': typeof AdminSubmissionsLazyRouteWithChildren
  '/onboarding/team': typeof OnboardingTeamLazyRouteWithChildren
  '/student/feedback': typeof StudentFeedbackLazyRoute
  '/student/grades': typeof StudentGradesLazyRoute
  '/student/meetings': typeof StudentMeetingsLazyRouteWithChildren
  '/student/notices': typeof StudentNoticesLazyRouteWithChildren
  '/student/peer-review': typeof StudentPeerReviewLazyRoute
  '/student/presentation-evaluation': typeof StudentPresentationEvaluationLazyRoute
  '/student/project-topic': typeof StudentProjectTopicLazyRoute
  '/student/team': typeof StudentTeamLazyRoute
  '/admin/': typeof AdminIndexLazyRoute
  '/student/': typeof StudentIndexLazyRoute
  '/admin/meetings/$meetingId': typeof AdminMeetingsMeetingIdLazyRoute
  '/admin/milestones/new': typeof AdminMilestonesNewLazyRoute
  '/admin/notices/$noticeId': typeof AdminNoticesNoticeIdLazyRouteWithChildren
  '/admin/notices/new': typeof AdminNoticesNewLazyRoute
  '/admin/submissions/$submissionId': typeof AdminSubmissionsSubmissionIdLazyRoute
  '/admin/teams/$teamId': typeof AdminTeamsTeamIdLazyRoute
  '/onboarding/team/first-meeting': typeof OnboardingTeamFirstMeetingLazyRoute
  '/onboarding/team/result': typeof OnboardingTeamResultLazyRoute
  '/onboarding/team/survey': typeof OnboardingTeamSurveyLazyRoute
  '/student/meetings/$meetingId': typeof StudentMeetingsMeetingIdLazyRouteWithChildren
  '/student/meetings/new': typeof StudentMeetingsNewLazyRoute
  '/student/notices/$noticeId': typeof StudentNoticesNoticeIdLazyRouteWithChildren
  '/admin/meetings/': typeof AdminMeetingsIndexLazyRoute
  '/admin/milestones/': typeof AdminMilestonesIndexLazyRoute
  '/admin/notices/': typeof AdminNoticesIndexLazyRoute
  '/admin/submissions/': typeof AdminSubmissionsIndexLazyRoute
  '/onboarding/team/': typeof OnboardingTeamIndexLazyRoute
  '/student/meetings/': typeof StudentMeetingsIndexLazyRoute
  '/student/notices/': typeof StudentNoticesIndexLazyRoute
  '/admin/notices/$noticeId/edit': typeof AdminNoticesNoticeIdEditLazyRoute
  '/student/editor/mid-review/$section': typeof StudentEditorMidReviewSectionLazyRoute
  '/student/editor/presentation/$section': typeof StudentEditorPresentationSectionLazyRoute
  '/student/editor/proposal/$section': typeof StudentEditorProposalSectionLazyRoute
  '/student/meetings/$meetingId/edit': typeof StudentMeetingsMeetingIdEditLazyRoute
  '/admin/notices/$noticeId/': typeof AdminNoticesNoticeIdIndexLazyRoute
  '/student/meetings/$meetingId/': typeof StudentMeetingsMeetingIdIndexLazyRoute
  '/student/notices/$noticeId/': typeof StudentNoticesNoticeIdIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/login': typeof LoginLazyRoute
  '/admin/profile': typeof AdminProfileLazyRoute
  '/admin/student-team': typeof AdminStudentTeamLazyRoute
  '/student/feedback': typeof StudentFeedbackLazyRoute
  '/student/grades': typeof StudentGradesLazyRoute
  '/student/peer-review': typeof StudentPeerReviewLazyRoute
  '/student/presentation-evaluation': typeof StudentPresentationEvaluationLazyRoute
  '/student/project-topic': typeof StudentProjectTopicLazyRoute
  '/student/team': typeof StudentTeamLazyRoute
  '/admin': typeof AdminIndexLazyRoute
  '/student': typeof StudentIndexLazyRoute
  '/admin/meetings/$meetingId': typeof AdminMeetingsMeetingIdLazyRoute
  '/admin/milestones/new': typeof AdminMilestonesNewLazyRoute
  '/admin/notices/new': typeof AdminNoticesNewLazyRoute
  '/admin/submissions/$submissionId': typeof AdminSubmissionsSubmissionIdLazyRoute
  '/admin/teams/$teamId': typeof AdminTeamsTeamIdLazyRoute
  '/onboarding/team/first-meeting': typeof OnboardingTeamFirstMeetingLazyRoute
  '/onboarding/team/result': typeof OnboardingTeamResultLazyRoute
  '/onboarding/team/survey': typeof OnboardingTeamSurveyLazyRoute
  '/student/meetings/new': typeof StudentMeetingsNewLazyRoute
  '/admin/meetings': typeof AdminMeetingsIndexLazyRoute
  '/admin/milestones': typeof AdminMilestonesIndexLazyRoute
  '/admin/notices': typeof AdminNoticesIndexLazyRoute
  '/admin/submissions': typeof AdminSubmissionsIndexLazyRoute
  '/onboarding/team': typeof OnboardingTeamIndexLazyRoute
  '/student/meetings': typeof StudentMeetingsIndexLazyRoute
  '/student/notices': typeof StudentNoticesIndexLazyRoute
  '/admin/notices/$noticeId/edit': typeof AdminNoticesNoticeIdEditLazyRoute
  '/student/editor/mid-review/$section': typeof StudentEditorMidReviewSectionLazyRoute
  '/student/editor/presentation/$section': typeof StudentEditorPresentationSectionLazyRoute
  '/student/editor/proposal/$section': typeof StudentEditorProposalSectionLazyRoute
  '/student/meetings/$meetingId/edit': typeof StudentMeetingsMeetingIdEditLazyRoute
  '/admin/notices/$noticeId': typeof AdminNoticesNoticeIdIndexLazyRoute
  '/student/meetings/$meetingId': typeof StudentMeetingsMeetingIdIndexLazyRoute
  '/student/notices/$noticeId': typeof StudentNoticesNoticeIdIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/admin': typeof AdminLazyRouteWithChildren
  '/login': typeof LoginLazyRoute
  '/student': typeof StudentLazyRouteWithChildren
  '/admin/meetings': typeof AdminMeetingsLazyRouteWithChildren
  '/admin/notices': typeof AdminNoticesLazyRouteWithChildren
  '/admin/profile': typeof AdminProfileLazyRoute
  '/admin/student-team': typeof AdminStudentTeamLazyRoute
  '/admin/submissions': typeof AdminSubmissionsLazyRouteWithChildren
  '/onboarding/team': typeof OnboardingTeamLazyRouteWithChildren
  '/student/feedback': typeof StudentFeedbackLazyRoute
  '/student/grades': typeof StudentGradesLazyRoute
  '/student/meetings': typeof StudentMeetingsLazyRouteWithChildren
  '/student/notices': typeof StudentNoticesLazyRouteWithChildren
  '/student/peer-review': typeof StudentPeerReviewLazyRoute
  '/student/presentation-evaluation': typeof StudentPresentationEvaluationLazyRoute
  '/student/project-topic': typeof StudentProjectTopicLazyRoute
  '/student/team': typeof StudentTeamLazyRoute
  '/admin/': typeof AdminIndexLazyRoute
  '/student/': typeof StudentIndexLazyRoute
  '/admin/meetings/$meetingId': typeof AdminMeetingsMeetingIdLazyRoute
  '/admin/milestones/new': typeof AdminMilestonesNewLazyRoute
  '/admin/notices/$noticeId': typeof AdminNoticesNoticeIdLazyRouteWithChildren
  '/admin/notices/new': typeof AdminNoticesNewLazyRoute
  '/admin/submissions/$submissionId': typeof AdminSubmissionsSubmissionIdLazyRoute
  '/admin/teams/$teamId': typeof AdminTeamsTeamIdLazyRoute
  '/onboarding/team/first-meeting': typeof OnboardingTeamFirstMeetingLazyRoute
  '/onboarding/team/result': typeof OnboardingTeamResultLazyRoute
  '/onboarding/team/survey': typeof OnboardingTeamSurveyLazyRoute
  '/student/meetings/$meetingId': typeof StudentMeetingsMeetingIdLazyRouteWithChildren
  '/student/meetings/new': typeof StudentMeetingsNewLazyRoute
  '/student/notices/$noticeId': typeof StudentNoticesNoticeIdLazyRouteWithChildren
  '/admin/meetings/': typeof AdminMeetingsIndexLazyRoute
  '/admin/milestones/': typeof AdminMilestonesIndexLazyRoute
  '/admin/notices/': typeof AdminNoticesIndexLazyRoute
  '/admin/submissions/': typeof AdminSubmissionsIndexLazyRoute
  '/onboarding/team/': typeof OnboardingTeamIndexLazyRoute
  '/student/meetings/': typeof StudentMeetingsIndexLazyRoute
  '/student/notices/': typeof StudentNoticesIndexLazyRoute
  '/admin/notices/$noticeId/edit': typeof AdminNoticesNoticeIdEditLazyRoute
  '/student/editor/mid-review/$section': typeof StudentEditorMidReviewSectionLazyRoute
  '/student/editor/presentation/$section': typeof StudentEditorPresentationSectionLazyRoute
  '/student/editor/proposal/$section': typeof StudentEditorProposalSectionLazyRoute
  '/student/meetings/$meetingId/edit': typeof StudentMeetingsMeetingIdEditLazyRoute
  '/admin/notices/$noticeId/': typeof AdminNoticesNoticeIdIndexLazyRoute
  '/student/meetings/$meetingId/': typeof StudentMeetingsMeetingIdIndexLazyRoute
  '/student/notices/$noticeId/': typeof StudentNoticesNoticeIdIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/student'
    | '/admin/meetings'
    | '/admin/notices'
    | '/admin/profile'
    | '/admin/student-team'
    | '/admin/submissions'
    | '/onboarding/team'
    | '/student/feedback'
    | '/student/grades'
    | '/student/meetings'
    | '/student/notices'
    | '/student/peer-review'
    | '/student/presentation-evaluation'
    | '/student/project-topic'
    | '/student/team'
    | '/admin/'
    | '/student/'
    | '/admin/meetings/$meetingId'
    | '/admin/milestones/new'
    | '/admin/notices/$noticeId'
    | '/admin/notices/new'
    | '/admin/submissions/$submissionId'
    | '/admin/teams/$teamId'
    | '/onboarding/team/first-meeting'
    | '/onboarding/team/result'
    | '/onboarding/team/survey'
    | '/student/meetings/$meetingId'
    | '/student/meetings/new'
    | '/student/notices/$noticeId'
    | '/admin/meetings/'
    | '/admin/milestones/'
    | '/admin/notices/'
    | '/admin/submissions/'
    | '/onboarding/team/'
    | '/student/meetings/'
    | '/student/notices/'
    | '/admin/notices/$noticeId/edit'
    | '/student/editor/mid-review/$section'
    | '/student/editor/presentation/$section'
    | '/student/editor/proposal/$section'
    | '/student/meetings/$meetingId/edit'
    | '/admin/notices/$noticeId/'
    | '/student/meetings/$meetingId/'
    | '/student/notices/$noticeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/profile'
    | '/admin/student-team'
    | '/student/feedback'
    | '/student/grades'
    | '/student/peer-review'
    | '/student/presentation-evaluation'
    | '/student/project-topic'
    | '/student/team'
    | '/admin'
    | '/student'
    | '/admin/meetings/$meetingId'
    | '/admin/milestones/new'
    | '/admin/notices/new'
    | '/admin/submissions/$submissionId'
    | '/admin/teams/$teamId'
    | '/onboarding/team/first-meeting'
    | '/onboarding/team/result'
    | '/onboarding/team/survey'
    | '/student/meetings/new'
    | '/admin/meetings'
    | '/admin/milestones'
    | '/admin/notices'
    | '/admin/submissions'
    | '/onboarding/team'
    | '/student/meetings'
    | '/student/notices'
    | '/admin/notices/$noticeId/edit'
    | '/student/editor/mid-review/$section'
    | '/student/editor/presentation/$section'
    | '/student/editor/proposal/$section'
    | '/student/meetings/$meetingId/edit'
    | '/admin/notices/$noticeId'
    | '/student/meetings/$meetingId'
    | '/student/notices/$noticeId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/student'
    | '/admin/meetings'
    | '/admin/notices'
    | '/admin/profile'
    | '/admin/student-team'
    | '/admin/submissions'
    | '/onboarding/team'
    | '/student/feedback'
    | '/student/grades'
    | '/student/meetings'
    | '/student/notices'
    | '/student/peer-review'
    | '/student/presentation-evaluation'
    | '/student/project-topic'
    | '/student/team'
    | '/admin/'
    | '/student/'
    | '/admin/meetings/$meetingId'
    | '/admin/milestones/new'
    | '/admin/notices/$noticeId'
    | '/admin/notices/new'
    | '/admin/submissions/$submissionId'
    | '/admin/teams/$teamId'
    | '/onboarding/team/first-meeting'
    | '/onboarding/team/result'
    | '/onboarding/team/survey'
    | '/student/meetings/$meetingId'
    | '/student/meetings/new'
    | '/student/notices/$noticeId'
    | '/admin/meetings/'
    | '/admin/milestones/'
    | '/admin/notices/'
    | '/admin/submissions/'
    | '/onboarding/team/'
    | '/student/meetings/'
    | '/student/notices/'
    | '/admin/notices/$noticeId/edit'
    | '/student/editor/mid-review/$section'
    | '/student/editor/presentation/$section'
    | '/student/editor/proposal/$section'
    | '/student/meetings/$meetingId/edit'
    | '/admin/notices/$noticeId/'
    | '/student/meetings/$meetingId/'
    | '/student/notices/$noticeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AdminLazyRoute: typeof AdminLazyRouteWithChildren
  LoginLazyRoute: typeof LoginLazyRoute
  StudentLazyRoute: typeof StudentLazyRouteWithChildren
  OnboardingTeamLazyRoute: typeof OnboardingTeamLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexLazyRouteImport
      parentRoute: typeof StudentLazyRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexLazyRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/student/team': {
      id: '/student/team'
      path: '/team'
      fullPath: '/student/team'
      preLoaderRoute: typeof StudentTeamLazyRouteImport
      parentRoute: typeof StudentLazyRoute
    }
    '/student/project-topic': {
      id: '/student/project-topic'
      path: '/project-topic'
      fullPath: '/student/project-topic'
      preLoaderRoute: typeof StudentProjectTopicLazyRouteImport
      parentRoute: typeof StudentLazyRoute
    }
    '/student/presentation-evaluation': {
      id: '/student/presentation-evaluation'
      path: '/presentation-evaluation'
      fullPath: '/student/presentation-evaluation'
      preLoaderRoute: typeof StudentPresentationEvaluationLazyRouteImport
      parentRoute: typeof StudentLazyRoute
    }
    '/student/peer-review': {
      id: '/student/peer-review'
      path: '/peer-review'
      fullPath: '/student/peer-review'
      preLoaderRoute: typeof StudentPeerReviewLazyRouteImport
      parentRoute: typeof StudentLazyRoute
    }
    '/student/notices': {
      id: '/student/notices'
      path: '/notices'
      fullPath: '/student/notices'
      preLoaderRoute: typeof StudentNoticesLazyRouteImport
      parentRoute: typeof StudentLazyRoute
    }
    '/student/meetings': {
      id: '/student/meetings'
      path: '/meetings'
      fullPath: '/student/meetings'
      preLoaderRoute: typeof StudentMeetingsLazyRouteImport
      parentRoute: typeof StudentLazyRoute
    }
    '/student/grades': {
      id: '/student/grades'
      path: '/grades'
      fullPath: '/student/grades'
      preLoaderRoute: typeof StudentGradesLazyRouteImport
      parentRoute: typeof StudentLazyRoute
    }
    '/student/feedback': {
      id: '/student/feedback'
      path: '/feedback'
      fullPath: '/student/feedback'
      preLoaderRoute: typeof StudentFeedbackLazyRouteImport
      parentRoute: typeof StudentLazyRoute
    }
    '/onboarding/team': {
      id: '/onboarding/team'
      path: '/onboarding/team'
      fullPath: '/onboarding/team'
      preLoaderRoute: typeof OnboardingTeamLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsLazyRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/admin/student-team': {
      id: '/admin/student-team'
      path: '/student-team'
      fullPath: '/admin/student-team'
      preLoaderRoute: typeof AdminStudentTeamLazyRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileLazyRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/admin/notices': {
      id: '/admin/notices'
      path: '/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AdminNoticesLazyRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/admin/meetings': {
      id: '/admin/meetings'
      path: '/meetings'
      fullPath: '/admin/meetings'
      preLoaderRoute: typeof AdminMeetingsLazyRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/student/notices/': {
      id: '/student/notices/'
      path: '/'
      fullPath: '/student/notices/'
      preLoaderRoute: typeof StudentNoticesIndexLazyRouteImport
      parentRoute: typeof StudentNoticesLazyRoute
    }
    '/student/meetings/': {
      id: '/student/meetings/'
      path: '/'
      fullPath: '/student/meetings/'
      preLoaderRoute: typeof StudentMeetingsIndexLazyRouteImport
      parentRoute: typeof StudentMeetingsLazyRoute
    }
    '/onboarding/team/': {
      id: '/onboarding/team/'
      path: '/'
      fullPath: '/onboarding/team/'
      preLoaderRoute: typeof OnboardingTeamIndexLazyRouteImport
      parentRoute: typeof OnboardingTeamLazyRoute
    }
    '/admin/submissions/': {
      id: '/admin/submissions/'
      path: '/'
      fullPath: '/admin/submissions/'
      preLoaderRoute: typeof AdminSubmissionsIndexLazyRouteImport
      parentRoute: typeof AdminSubmissionsLazyRoute
    }
    '/admin/notices/': {
      id: '/admin/notices/'
      path: '/'
      fullPath: '/admin/notices/'
      preLoaderRoute: typeof AdminNoticesIndexLazyRouteImport
      parentRoute: typeof AdminNoticesLazyRoute
    }
    '/admin/milestones/': {
      id: '/admin/milestones/'
      path: '/milestones'
      fullPath: '/admin/milestones/'
      preLoaderRoute: typeof AdminMilestonesIndexLazyRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/admin/meetings/': {
      id: '/admin/meetings/'
      path: '/'
      fullPath: '/admin/meetings/'
      preLoaderRoute: typeof AdminMeetingsIndexLazyRouteImport
      parentRoute: typeof AdminMeetingsLazyRoute
    }
    '/student/notices/$noticeId': {
      id: '/student/notices/$noticeId'
      path: '/$noticeId'
      fullPath: '/student/notices/$noticeId'
      preLoaderRoute: typeof StudentNoticesNoticeIdLazyRouteImport
      parentRoute: typeof StudentNoticesLazyRoute
    }
    '/student/meetings/new': {
      id: '/student/meetings/new'
      path: '/new'
      fullPath: '/student/meetings/new'
      preLoaderRoute: typeof StudentMeetingsNewLazyRouteImport
      parentRoute: typeof StudentMeetingsLazyRoute
    }
    '/student/meetings/$meetingId': {
      id: '/student/meetings/$meetingId'
      path: '/$meetingId'
      fullPath: '/student/meetings/$meetingId'
      preLoaderRoute: typeof StudentMeetingsMeetingIdLazyRouteImport
      parentRoute: typeof StudentMeetingsLazyRoute
    }
    '/onboarding/team/survey': {
      id: '/onboarding/team/survey'
      path: '/survey'
      fullPath: '/onboarding/team/survey'
      preLoaderRoute: typeof OnboardingTeamSurveyLazyRouteImport
      parentRoute: typeof OnboardingTeamLazyRoute
    }
    '/onboarding/team/result': {
      id: '/onboarding/team/result'
      path: '/result'
      fullPath: '/onboarding/team/result'
      preLoaderRoute: typeof OnboardingTeamResultLazyRouteImport
      parentRoute: typeof OnboardingTeamLazyRoute
    }
    '/onboarding/team/first-meeting': {
      id: '/onboarding/team/first-meeting'
      path: '/first-meeting'
      fullPath: '/onboarding/team/first-meeting'
      preLoaderRoute: typeof OnboardingTeamFirstMeetingLazyRouteImport
      parentRoute: typeof OnboardingTeamLazyRoute
    }
    '/admin/teams/$teamId': {
      id: '/admin/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/admin/teams/$teamId'
      preLoaderRoute: typeof AdminTeamsTeamIdLazyRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/admin/submissions/$submissionId': {
      id: '/admin/submissions/$submissionId'
      path: '/$submissionId'
      fullPath: '/admin/submissions/$submissionId'
      preLoaderRoute: typeof AdminSubmissionsSubmissionIdLazyRouteImport
      parentRoute: typeof AdminSubmissionsLazyRoute
    }
    '/admin/notices/new': {
      id: '/admin/notices/new'
      path: '/new'
      fullPath: '/admin/notices/new'
      preLoaderRoute: typeof AdminNoticesNewLazyRouteImport
      parentRoute: typeof AdminNoticesLazyRoute
    }
    '/admin/notices/$noticeId': {
      id: '/admin/notices/$noticeId'
      path: '/$noticeId'
      fullPath: '/admin/notices/$noticeId'
      preLoaderRoute: typeof AdminNoticesNoticeIdLazyRouteImport
      parentRoute: typeof AdminNoticesLazyRoute
    }
    '/admin/milestones/new': {
      id: '/admin/milestones/new'
      path: '/milestones/new'
      fullPath: '/admin/milestones/new'
      preLoaderRoute: typeof AdminMilestonesNewLazyRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/admin/meetings/$meetingId': {
      id: '/admin/meetings/$meetingId'
      path: '/$meetingId'
      fullPath: '/admin/meetings/$meetingId'
      preLoaderRoute: typeof AdminMeetingsMeetingIdLazyRouteImport
      parentRoute: typeof AdminMeetingsLazyRoute
    }
    '/student/notices/$noticeId/': {
      id: '/student/notices/$noticeId/'
      path: '/'
      fullPath: '/student/notices/$noticeId/'
      preLoaderRoute: typeof StudentNoticesNoticeIdIndexLazyRouteImport
      parentRoute: typeof StudentNoticesNoticeIdLazyRoute
    }
    '/student/meetings/$meetingId/': {
      id: '/student/meetings/$meetingId/'
      path: '/'
      fullPath: '/student/meetings/$meetingId/'
      preLoaderRoute: typeof StudentMeetingsMeetingIdIndexLazyRouteImport
      parentRoute: typeof StudentMeetingsMeetingIdLazyRoute
    }
    '/admin/notices/$noticeId/': {
      id: '/admin/notices/$noticeId/'
      path: '/'
      fullPath: '/admin/notices/$noticeId/'
      preLoaderRoute: typeof AdminNoticesNoticeIdIndexLazyRouteImport
      parentRoute: typeof AdminNoticesNoticeIdLazyRoute
    }
    '/student/meetings/$meetingId/edit': {
      id: '/student/meetings/$meetingId/edit'
      path: '/edit'
      fullPath: '/student/meetings/$meetingId/edit'
      preLoaderRoute: typeof StudentMeetingsMeetingIdEditLazyRouteImport
      parentRoute: typeof StudentMeetingsMeetingIdLazyRoute
    }
    '/student/editor/proposal/$section': {
      id: '/student/editor/proposal/$section'
      path: '/editor/proposal/$section'
      fullPath: '/student/editor/proposal/$section'
      preLoaderRoute: typeof StudentEditorProposalSectionLazyRouteImport
      parentRoute: typeof StudentLazyRoute
    }
    '/student/editor/presentation/$section': {
      id: '/student/editor/presentation/$section'
      path: '/editor/presentation/$section'
      fullPath: '/student/editor/presentation/$section'
      preLoaderRoute: typeof StudentEditorPresentationSectionLazyRouteImport
      parentRoute: typeof StudentLazyRoute
    }
    '/student/editor/mid-review/$section': {
      id: '/student/editor/mid-review/$section'
      path: '/editor/mid-review/$section'
      fullPath: '/student/editor/mid-review/$section'
      preLoaderRoute: typeof StudentEditorMidReviewSectionLazyRouteImport
      parentRoute: typeof StudentLazyRoute
    }
    '/admin/notices/$noticeId/edit': {
      id: '/admin/notices/$noticeId/edit'
      path: '/edit'
      fullPath: '/admin/notices/$noticeId/edit'
      preLoaderRoute: typeof AdminNoticesNoticeIdEditLazyRouteImport
      parentRoute: typeof AdminNoticesNoticeIdLazyRoute
    }
  }
}

interface AdminMeetingsLazyRouteChildren {
  AdminMeetingsMeetingIdLazyRoute: typeof AdminMeetingsMeetingIdLazyRoute
  AdminMeetingsIndexLazyRoute: typeof AdminMeetingsIndexLazyRoute
}

const AdminMeetingsLazyRouteChildren: AdminMeetingsLazyRouteChildren = {
  AdminMeetingsMeetingIdLazyRoute: AdminMeetingsMeetingIdLazyRoute,
  AdminMeetingsIndexLazyRoute: AdminMeetingsIndexLazyRoute,
}

const AdminMeetingsLazyRouteWithChildren =
  AdminMeetingsLazyRoute._addFileChildren(AdminMeetingsLazyRouteChildren)

interface AdminNoticesNoticeIdLazyRouteChildren {
  AdminNoticesNoticeIdEditLazyRoute: typeof AdminNoticesNoticeIdEditLazyRoute
  AdminNoticesNoticeIdIndexLazyRoute: typeof AdminNoticesNoticeIdIndexLazyRoute
}

const AdminNoticesNoticeIdLazyRouteChildren: AdminNoticesNoticeIdLazyRouteChildren =
  {
    AdminNoticesNoticeIdEditLazyRoute: AdminNoticesNoticeIdEditLazyRoute,
    AdminNoticesNoticeIdIndexLazyRoute: AdminNoticesNoticeIdIndexLazyRoute,
  }

const AdminNoticesNoticeIdLazyRouteWithChildren =
  AdminNoticesNoticeIdLazyRoute._addFileChildren(
    AdminNoticesNoticeIdLazyRouteChildren,
  )

interface AdminNoticesLazyRouteChildren {
  AdminNoticesNoticeIdLazyRoute: typeof AdminNoticesNoticeIdLazyRouteWithChildren
  AdminNoticesNewLazyRoute: typeof AdminNoticesNewLazyRoute
  AdminNoticesIndexLazyRoute: typeof AdminNoticesIndexLazyRoute
}

const AdminNoticesLazyRouteChildren: AdminNoticesLazyRouteChildren = {
  AdminNoticesNoticeIdLazyRoute: AdminNoticesNoticeIdLazyRouteWithChildren,
  AdminNoticesNewLazyRoute: AdminNoticesNewLazyRoute,
  AdminNoticesIndexLazyRoute: AdminNoticesIndexLazyRoute,
}

const AdminNoticesLazyRouteWithChildren =
  AdminNoticesLazyRoute._addFileChildren(AdminNoticesLazyRouteChildren)

interface AdminSubmissionsLazyRouteChildren {
  AdminSubmissionsSubmissionIdLazyRoute: typeof AdminSubmissionsSubmissionIdLazyRoute
  AdminSubmissionsIndexLazyRoute: typeof AdminSubmissionsIndexLazyRoute
}

const AdminSubmissionsLazyRouteChildren: AdminSubmissionsLazyRouteChildren = {
  AdminSubmissionsSubmissionIdLazyRoute: AdminSubmissionsSubmissionIdLazyRoute,
  AdminSubmissionsIndexLazyRoute: AdminSubmissionsIndexLazyRoute,
}

const AdminSubmissionsLazyRouteWithChildren =
  AdminSubmissionsLazyRoute._addFileChildren(AdminSubmissionsLazyRouteChildren)

interface AdminLazyRouteChildren {
  AdminMeetingsLazyRoute: typeof AdminMeetingsLazyRouteWithChildren
  AdminNoticesLazyRoute: typeof AdminNoticesLazyRouteWithChildren
  AdminProfileLazyRoute: typeof AdminProfileLazyRoute
  AdminStudentTeamLazyRoute: typeof AdminStudentTeamLazyRoute
  AdminSubmissionsLazyRoute: typeof AdminSubmissionsLazyRouteWithChildren
  AdminIndexLazyRoute: typeof AdminIndexLazyRoute
  AdminMilestonesNewLazyRoute: typeof AdminMilestonesNewLazyRoute
  AdminTeamsTeamIdLazyRoute: typeof AdminTeamsTeamIdLazyRoute
  AdminMilestonesIndexLazyRoute: typeof AdminMilestonesIndexLazyRoute
}

const AdminLazyRouteChildren: AdminLazyRouteChildren = {
  AdminMeetingsLazyRoute: AdminMeetingsLazyRouteWithChildren,
  AdminNoticesLazyRoute: AdminNoticesLazyRouteWithChildren,
  AdminProfileLazyRoute: AdminProfileLazyRoute,
  AdminStudentTeamLazyRoute: AdminStudentTeamLazyRoute,
  AdminSubmissionsLazyRoute: AdminSubmissionsLazyRouteWithChildren,
  AdminIndexLazyRoute: AdminIndexLazyRoute,
  AdminMilestonesNewLazyRoute: AdminMilestonesNewLazyRoute,
  AdminTeamsTeamIdLazyRoute: AdminTeamsTeamIdLazyRoute,
  AdminMilestonesIndexLazyRoute: AdminMilestonesIndexLazyRoute,
}

const AdminLazyRouteWithChildren = AdminLazyRoute._addFileChildren(
  AdminLazyRouteChildren,
)

interface StudentMeetingsMeetingIdLazyRouteChildren {
  StudentMeetingsMeetingIdEditLazyRoute: typeof StudentMeetingsMeetingIdEditLazyRoute
  StudentMeetingsMeetingIdIndexLazyRoute: typeof StudentMeetingsMeetingIdIndexLazyRoute
}

const StudentMeetingsMeetingIdLazyRouteChildren: StudentMeetingsMeetingIdLazyRouteChildren =
  {
    StudentMeetingsMeetingIdEditLazyRoute:
      StudentMeetingsMeetingIdEditLazyRoute,
    StudentMeetingsMeetingIdIndexLazyRoute:
      StudentMeetingsMeetingIdIndexLazyRoute,
  }

const StudentMeetingsMeetingIdLazyRouteWithChildren =
  StudentMeetingsMeetingIdLazyRoute._addFileChildren(
    StudentMeetingsMeetingIdLazyRouteChildren,
  )

interface StudentMeetingsLazyRouteChildren {
  StudentMeetingsMeetingIdLazyRoute: typeof StudentMeetingsMeetingIdLazyRouteWithChildren
  StudentMeetingsNewLazyRoute: typeof StudentMeetingsNewLazyRoute
  StudentMeetingsIndexLazyRoute: typeof StudentMeetingsIndexLazyRoute
}

const StudentMeetingsLazyRouteChildren: StudentMeetingsLazyRouteChildren = {
  StudentMeetingsMeetingIdLazyRoute:
    StudentMeetingsMeetingIdLazyRouteWithChildren,
  StudentMeetingsNewLazyRoute: StudentMeetingsNewLazyRoute,
  StudentMeetingsIndexLazyRoute: StudentMeetingsIndexLazyRoute,
}

const StudentMeetingsLazyRouteWithChildren =
  StudentMeetingsLazyRoute._addFileChildren(StudentMeetingsLazyRouteChildren)

interface StudentNoticesNoticeIdLazyRouteChildren {
  StudentNoticesNoticeIdIndexLazyRoute: typeof StudentNoticesNoticeIdIndexLazyRoute
}

const StudentNoticesNoticeIdLazyRouteChildren: StudentNoticesNoticeIdLazyRouteChildren =
  {
    StudentNoticesNoticeIdIndexLazyRoute: StudentNoticesNoticeIdIndexLazyRoute,
  }

const StudentNoticesNoticeIdLazyRouteWithChildren =
  StudentNoticesNoticeIdLazyRoute._addFileChildren(
    StudentNoticesNoticeIdLazyRouteChildren,
  )

interface StudentNoticesLazyRouteChildren {
  StudentNoticesNoticeIdLazyRoute: typeof StudentNoticesNoticeIdLazyRouteWithChildren
  StudentNoticesIndexLazyRoute: typeof StudentNoticesIndexLazyRoute
}

const StudentNoticesLazyRouteChildren: StudentNoticesLazyRouteChildren = {
  StudentNoticesNoticeIdLazyRoute: StudentNoticesNoticeIdLazyRouteWithChildren,
  StudentNoticesIndexLazyRoute: StudentNoticesIndexLazyRoute,
}

const StudentNoticesLazyRouteWithChildren =
  StudentNoticesLazyRoute._addFileChildren(StudentNoticesLazyRouteChildren)

interface StudentLazyRouteChildren {
  StudentFeedbackLazyRoute: typeof StudentFeedbackLazyRoute
  StudentGradesLazyRoute: typeof StudentGradesLazyRoute
  StudentMeetingsLazyRoute: typeof StudentMeetingsLazyRouteWithChildren
  StudentNoticesLazyRoute: typeof StudentNoticesLazyRouteWithChildren
  StudentPeerReviewLazyRoute: typeof StudentPeerReviewLazyRoute
  StudentPresentationEvaluationLazyRoute: typeof StudentPresentationEvaluationLazyRoute
  StudentProjectTopicLazyRoute: typeof StudentProjectTopicLazyRoute
  StudentTeamLazyRoute: typeof StudentTeamLazyRoute
  StudentIndexLazyRoute: typeof StudentIndexLazyRoute
  StudentEditorMidReviewSectionLazyRoute: typeof StudentEditorMidReviewSectionLazyRoute
  StudentEditorPresentationSectionLazyRoute: typeof StudentEditorPresentationSectionLazyRoute
  StudentEditorProposalSectionLazyRoute: typeof StudentEditorProposalSectionLazyRoute
}

const StudentLazyRouteChildren: StudentLazyRouteChildren = {
  StudentFeedbackLazyRoute: StudentFeedbackLazyRoute,
  StudentGradesLazyRoute: StudentGradesLazyRoute,
  StudentMeetingsLazyRoute: StudentMeetingsLazyRouteWithChildren,
  StudentNoticesLazyRoute: StudentNoticesLazyRouteWithChildren,
  StudentPeerReviewLazyRoute: StudentPeerReviewLazyRoute,
  StudentPresentationEvaluationLazyRoute:
    StudentPresentationEvaluationLazyRoute,
  StudentProjectTopicLazyRoute: StudentProjectTopicLazyRoute,
  StudentTeamLazyRoute: StudentTeamLazyRoute,
  StudentIndexLazyRoute: StudentIndexLazyRoute,
  StudentEditorMidReviewSectionLazyRoute:
    StudentEditorMidReviewSectionLazyRoute,
  StudentEditorPresentationSectionLazyRoute:
    StudentEditorPresentationSectionLazyRoute,
  StudentEditorProposalSectionLazyRoute: StudentEditorProposalSectionLazyRoute,
}

const StudentLazyRouteWithChildren = StudentLazyRoute._addFileChildren(
  StudentLazyRouteChildren,
)

interface OnboardingTeamLazyRouteChildren {
  OnboardingTeamFirstMeetingLazyRoute: typeof OnboardingTeamFirstMeetingLazyRoute
  OnboardingTeamResultLazyRoute: typeof OnboardingTeamResultLazyRoute
  OnboardingTeamSurveyLazyRoute: typeof OnboardingTeamSurveyLazyRoute
  OnboardingTeamIndexLazyRoute: typeof OnboardingTeamIndexLazyRoute
}

const OnboardingTeamLazyRouteChildren: OnboardingTeamLazyRouteChildren = {
  OnboardingTeamFirstMeetingLazyRoute: OnboardingTeamFirstMeetingLazyRoute,
  OnboardingTeamResultLazyRoute: OnboardingTeamResultLazyRoute,
  OnboardingTeamSurveyLazyRoute: OnboardingTeamSurveyLazyRoute,
  OnboardingTeamIndexLazyRoute: OnboardingTeamIndexLazyRoute,
}

const OnboardingTeamLazyRouteWithChildren =
  OnboardingTeamLazyRoute._addFileChildren(OnboardingTeamLazyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AdminLazyRoute: AdminLazyRouteWithChildren,
  LoginLazyRoute: LoginLazyRoute,
  StudentLazyRoute: StudentLazyRouteWithChildren,
  OnboardingTeamLazyRoute: OnboardingTeamLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
