/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const StudentLazyRouteImport = createFileRoute('/student')()
const LoginLazyRouteImport = createFileRoute('/login')()
const AdminLazyRouteImport = createFileRoute('/admin')()
const IndexLazyRouteImport = createFileRoute('/')()
const StudentIndexLazyRouteImport = createFileRoute('/student/')()
const AdminIndexLazyRouteImport = createFileRoute('/admin/')()
const StudentTeamLazyRouteImport = createFileRoute('/student/team')()
const StudentProjectTopicLazyRouteImport = createFileRoute(
  '/student/project-topic',
)()
const StudentPresentationEvaluationLazyRouteImport = createFileRoute(
  '/student/presentation-evaluation',
)()
const StudentPeerReviewLazyRouteImport = createFileRoute(
  '/student/peer-review',
)()
const StudentGradesLazyRouteImport = createFileRoute('/student/grades')()
const StudentFeedbackLazyRouteImport = createFileRoute('/student/feedback')()
const OnboardingTeamLazyRouteImport = createFileRoute('/onboarding/team')()
const AdminStudentTeamLazyRouteImport = createFileRoute('/admin/student-team')()
const AdminNoticesLazyRouteImport = createFileRoute('/admin/notices')()
const OnboardingTeamIndexLazyRouteImport =
  createFileRoute('/onboarding/team/')()
const AdminNoticesIndexLazyRouteImport = createFileRoute('/admin/notices/')()
const OnboardingTeamSurveyLazyRouteImport = createFileRoute(
  '/onboarding/team/survey',
)()
const OnboardingTeamResultLazyRouteImport = createFileRoute(
  '/onboarding/team/result',
)()
const OnboardingTeamFirstMeetingLazyRouteImport = createFileRoute(
  '/onboarding/team/first-meeting',
)()
const AdminNoticesNewLazyRouteImport = createFileRoute('/admin/notices/new')()
const AdminNoticesNoticeIdLazyRouteImport = createFileRoute(
  '/admin/notices/$noticeId',
)()
const AdminNoticesNoticeIdIndexLazyRouteImport = createFileRoute(
  '/admin/notices/$noticeId/',
)()
const StudentEditorProposalSectionLazyRouteImport = createFileRoute(
  '/student/editor/proposal/$section',
)()
const StudentEditorPresentationSectionLazyRouteImport = createFileRoute(
  '/student/editor/presentation/$section',
)()
const StudentEditorMidReviewSectionLazyRouteImport = createFileRoute(
  '/student/editor/mid-review/$section',
)()
const AdminNoticesNoticeIdEditLazyRouteImport = createFileRoute(
  '/admin/notices/$noticeId/edit',
)()

const StudentLazyRoute = StudentLazyRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/student.lazy').then((d) => d.Route))
const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const AdminLazyRoute = AdminLazyRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const StudentIndexLazyRoute = StudentIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentLazyRoute,
} as any).lazy(() => import('./routes/student.index.lazy').then((d) => d.Route))
const AdminIndexLazyRoute = AdminIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLazyRoute,
} as any).lazy(() => import('./routes/admin.index.lazy').then((d) => d.Route))
const StudentTeamLazyRoute = StudentTeamLazyRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => StudentLazyRoute,
} as any).lazy(() => import('./routes/student.team.lazy').then((d) => d.Route))
const StudentProjectTopicLazyRoute = StudentProjectTopicLazyRouteImport.update({
  id: '/project-topic',
  path: '/project-topic',
  getParentRoute: () => StudentLazyRoute,
} as any).lazy(() =>
  import('./routes/student.project-topic.lazy').then((d) => d.Route),
)
const StudentPresentationEvaluationLazyRoute =
  StudentPresentationEvaluationLazyRouteImport.update({
    id: '/presentation-evaluation',
    path: '/presentation-evaluation',
    getParentRoute: () => StudentLazyRoute,
  } as any).lazy(() =>
    import('./routes/student.presentation-evaluation.lazy').then(
      (d) => d.Route,
    ),
  )
const StudentPeerReviewLazyRoute = StudentPeerReviewLazyRouteImport.update({
  id: '/peer-review',
  path: '/peer-review',
  getParentRoute: () => StudentLazyRoute,
} as any).lazy(() =>
  import('./routes/student.peer-review.lazy').then((d) => d.Route),
)
const StudentGradesLazyRoute = StudentGradesLazyRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => StudentLazyRoute,
} as any).lazy(() =>
  import('./routes/student.grades.lazy').then((d) => d.Route),
)
const StudentFeedbackLazyRoute = StudentFeedbackLazyRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => StudentLazyRoute,
} as any).lazy(() =>
  import('./routes/student.feedback.lazy').then((d) => d.Route),
)
const OnboardingTeamLazyRoute = OnboardingTeamLazyRouteImport.update({
  id: '/onboarding/team',
  path: '/onboarding/team',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/onboarding.team.lazy').then((d) => d.Route),
)
const AdminStudentTeamLazyRoute = AdminStudentTeamLazyRouteImport.update({
  id: '/student-team',
  path: '/student-team',
  getParentRoute: () => AdminLazyRoute,
} as any).lazy(() =>
  import('./routes/admin.student-team.lazy').then((d) => d.Route),
)
const AdminNoticesLazyRoute = AdminNoticesLazyRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AdminLazyRoute,
} as any).lazy(() => import('./routes/admin.notices.lazy').then((d) => d.Route))
const OnboardingTeamIndexLazyRoute = OnboardingTeamIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingTeamLazyRoute,
} as any).lazy(() =>
  import('./routes/onboarding.team.index.lazy').then((d) => d.Route),
)
const AdminNoticesIndexLazyRoute = AdminNoticesIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminNoticesLazyRoute,
} as any).lazy(() =>
  import('./routes/admin.notices.index.lazy').then((d) => d.Route),
)
const OnboardingTeamSurveyLazyRoute =
  OnboardingTeamSurveyLazyRouteImport.update({
    id: '/survey',
    path: '/survey',
    getParentRoute: () => OnboardingTeamLazyRoute,
  } as any).lazy(() =>
    import('./routes/onboarding.team.survey.lazy').then((d) => d.Route),
  )
const OnboardingTeamResultLazyRoute =
  OnboardingTeamResultLazyRouteImport.update({
    id: '/result',
    path: '/result',
    getParentRoute: () => OnboardingTeamLazyRoute,
  } as any).lazy(() =>
    import('./routes/onboarding.team.result.lazy').then((d) => d.Route),
  )
const OnboardingTeamFirstMeetingLazyRoute =
  OnboardingTeamFirstMeetingLazyRouteImport.update({
    id: '/first-meeting',
    path: '/first-meeting',
    getParentRoute: () => OnboardingTeamLazyRoute,
  } as any).lazy(() =>
    import('./routes/onboarding.team.first-meeting.lazy').then((d) => d.Route),
  )
const AdminNoticesNewLazyRoute = AdminNoticesNewLazyRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminNoticesLazyRoute,
} as any).lazy(() =>
  import('./routes/admin.notices.new.lazy').then((d) => d.Route),
)
const AdminNoticesNoticeIdLazyRoute =
  AdminNoticesNoticeIdLazyRouteImport.update({
    id: '/$noticeId',
    path: '/$noticeId',
    getParentRoute: () => AdminNoticesLazyRoute,
  } as any).lazy(() =>
    import('./routes/admin.notices.$noticeId.lazy').then((d) => d.Route),
  )
const AdminNoticesNoticeIdIndexLazyRoute =
  AdminNoticesNoticeIdIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminNoticesNoticeIdLazyRoute,
  } as any).lazy(() =>
    import('./routes/admin.notices.$noticeId.index.lazy').then((d) => d.Route),
  )
const StudentEditorProposalSectionLazyRoute =
  StudentEditorProposalSectionLazyRouteImport.update({
    id: '/editor/proposal/$section',
    path: '/editor/proposal/$section',
    getParentRoute: () => StudentLazyRoute,
  } as any).lazy(() =>
    import('./routes/student.editor.proposal.$section.lazy').then(
      (d) => d.Route,
    ),
  )
const StudentEditorPresentationSectionLazyRoute =
  StudentEditorPresentationSectionLazyRouteImport.update({
    id: '/editor/presentation/$section',
    path: '/editor/presentation/$section',
    getParentRoute: () => StudentLazyRoute,
  } as any).lazy(() =>
    import('./routes/student.editor.presentation.$section.lazy').then(
      (d) => d.Route,
    ),
  )
const StudentEditorMidReviewSectionLazyRoute =
  StudentEditorMidReviewSectionLazyRouteImport.update({
    id: '/editor/mid-review/$section',
    path: '/editor/mid-review/$section',
    getParentRoute: () => StudentLazyRoute,
  } as any).lazy(() =>
    import('./routes/student.editor.mid-review.$section.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminNoticesNoticeIdEditLazyRoute =
  AdminNoticesNoticeIdEditLazyRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AdminNoticesNoticeIdLazyRoute,
  } as any).lazy(() =>
    import('./routes/admin.notices.$noticeId.edit.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/admin': typeof AdminLazyRouteWithChildren
  '/login': typeof LoginLazyRoute
  '/student': typeof StudentLazyRouteWithChildren
  '/admin/notices': typeof AdminNoticesLazyRouteWithChildren
  '/admin/student-team': typeof AdminStudentTeamLazyRoute
  '/onboarding/team': typeof OnboardingTeamLazyRouteWithChildren
  '/student/feedback': typeof StudentFeedbackLazyRoute
  '/student/grades': typeof StudentGradesLazyRoute
  '/student/peer-review': typeof StudentPeerReviewLazyRoute
  '/student/presentation-evaluation': typeof StudentPresentationEvaluationLazyRoute
  '/student/project-topic': typeof StudentProjectTopicLazyRoute
  '/student/team': typeof StudentTeamLazyRoute
  '/admin/': typeof AdminIndexLazyRoute
  '/student/': typeof StudentIndexLazyRoute
  '/admin/notices/$noticeId': typeof AdminNoticesNoticeIdLazyRouteWithChildren
  '/admin/notices/new': typeof AdminNoticesNewLazyRoute
  '/onboarding/team/first-meeting': typeof OnboardingTeamFirstMeetingLazyRoute
  '/onboarding/team/result': typeof OnboardingTeamResultLazyRoute
  '/onboarding/team/survey': typeof OnboardingTeamSurveyLazyRoute
  '/admin/notices/': typeof AdminNoticesIndexLazyRoute
  '/onboarding/team/': typeof OnboardingTeamIndexLazyRoute
  '/admin/notices/$noticeId/edit': typeof AdminNoticesNoticeIdEditLazyRoute
  '/student/editor/mid-review/$section': typeof StudentEditorMidReviewSectionLazyRoute
  '/student/editor/presentation/$section': typeof StudentEditorPresentationSectionLazyRoute
  '/student/editor/proposal/$section': typeof StudentEditorProposalSectionLazyRoute
  '/admin/notices/$noticeId/': typeof AdminNoticesNoticeIdIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/login': typeof LoginLazyRoute
  '/admin/student-team': typeof AdminStudentTeamLazyRoute
  '/student/feedback': typeof StudentFeedbackLazyRoute
  '/student/grades': typeof StudentGradesLazyRoute
  '/student/peer-review': typeof StudentPeerReviewLazyRoute
  '/student/presentation-evaluation': typeof StudentPresentationEvaluationLazyRoute
  '/student/project-topic': typeof StudentProjectTopicLazyRoute
  '/student/team': typeof StudentTeamLazyRoute
  '/admin': typeof AdminIndexLazyRoute
  '/student': typeof StudentIndexLazyRoute
  '/admin/notices/new': typeof AdminNoticesNewLazyRoute
  '/onboarding/team/first-meeting': typeof OnboardingTeamFirstMeetingLazyRoute
  '/onboarding/team/result': typeof OnboardingTeamResultLazyRoute
  '/onboarding/team/survey': typeof OnboardingTeamSurveyLazyRoute
  '/admin/notices': typeof AdminNoticesIndexLazyRoute
  '/onboarding/team': typeof OnboardingTeamIndexLazyRoute
  '/admin/notices/$noticeId/edit': typeof AdminNoticesNoticeIdEditLazyRoute
  '/student/editor/mid-review/$section': typeof StudentEditorMidReviewSectionLazyRoute
  '/student/editor/presentation/$section': typeof StudentEditorPresentationSectionLazyRoute
  '/student/editor/proposal/$section': typeof StudentEditorProposalSectionLazyRoute
  '/admin/notices/$noticeId': typeof AdminNoticesNoticeIdIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/admin': typeof AdminLazyRouteWithChildren
  '/login': typeof LoginLazyRoute
  '/student': typeof StudentLazyRouteWithChildren
  '/admin/notices': typeof AdminNoticesLazyRouteWithChildren
  '/admin/student-team': typeof AdminStudentTeamLazyRoute
  '/onboarding/team': typeof OnboardingTeamLazyRouteWithChildren
  '/student/feedback': typeof StudentFeedbackLazyRoute
  '/student/grades': typeof StudentGradesLazyRoute
  '/student/peer-review': typeof StudentPeerReviewLazyRoute
  '/student/presentation-evaluation': typeof StudentPresentationEvaluationLazyRoute
  '/student/project-topic': typeof StudentProjectTopicLazyRoute
  '/student/team': typeof StudentTeamLazyRoute
  '/admin/': typeof AdminIndexLazyRoute
  '/student/': typeof StudentIndexLazyRoute
  '/admin/notices/$noticeId': typeof AdminNoticesNoticeIdLazyRouteWithChildren
  '/admin/notices/new': typeof AdminNoticesNewLazyRoute
  '/onboarding/team/first-meeting': typeof OnboardingTeamFirstMeetingLazyRoute
  '/onboarding/team/result': typeof OnboardingTeamResultLazyRoute
  '/onboarding/team/survey': typeof OnboardingTeamSurveyLazyRoute
  '/admin/notices/': typeof AdminNoticesIndexLazyRoute
  '/onboarding/team/': typeof OnboardingTeamIndexLazyRoute
  '/admin/notices/$noticeId/edit': typeof AdminNoticesNoticeIdEditLazyRoute
  '/student/editor/mid-review/$section': typeof StudentEditorMidReviewSectionLazyRoute
  '/student/editor/presentation/$section': typeof StudentEditorPresentationSectionLazyRoute
  '/student/editor/proposal/$section': typeof StudentEditorProposalSectionLazyRoute
  '/admin/notices/$noticeId/': typeof AdminNoticesNoticeIdIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/student'
    | '/admin/notices'
    | '/admin/student-team'
    | '/onboarding/team'
    | '/student/feedback'
    | '/student/grades'
    | '/student/peer-review'
    | '/student/presentation-evaluation'
    | '/student/project-topic'
    | '/student/team'
    | '/admin/'
    | '/student/'
    | '/admin/notices/$noticeId'
    | '/admin/notices/new'
    | '/onboarding/team/first-meeting'
    | '/onboarding/team/result'
    | '/onboarding/team/survey'
    | '/admin/notices/'
    | '/onboarding/team/'
    | '/admin/notices/$noticeId/edit'
    | '/student/editor/mid-review/$section'
    | '/student/editor/presentation/$section'
    | '/student/editor/proposal/$section'
    | '/admin/notices/$noticeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/student-team'
    | '/student/feedback'
    | '/student/grades'
    | '/student/peer-review'
    | '/student/presentation-evaluation'
    | '/student/project-topic'
    | '/student/team'
    | '/admin'
    | '/student'
    | '/admin/notices/new'
    | '/onboarding/team/first-meeting'
    | '/onboarding/team/result'
    | '/onboarding/team/survey'
    | '/admin/notices'
    | '/onboarding/team'
    | '/admin/notices/$noticeId/edit'
    | '/student/editor/mid-review/$section'
    | '/student/editor/presentation/$section'
    | '/student/editor/proposal/$section'
    | '/admin/notices/$noticeId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/student'
    | '/admin/notices'
    | '/admin/student-team'
    | '/onboarding/team'
    | '/student/feedback'
    | '/student/grades'
    | '/student/peer-review'
    | '/student/presentation-evaluation'
    | '/student/project-topic'
    | '/student/team'
    | '/admin/'
    | '/student/'
    | '/admin/notices/$noticeId'
    | '/admin/notices/new'
    | '/onboarding/team/first-meeting'
    | '/onboarding/team/result'
    | '/onboarding/team/survey'
    | '/admin/notices/'
    | '/onboarding/team/'
    | '/admin/notices/$noticeId/edit'
    | '/student/editor/mid-review/$section'
    | '/student/editor/presentation/$section'
    | '/student/editor/proposal/$section'
    | '/admin/notices/$noticeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AdminLazyRoute: typeof AdminLazyRouteWithChildren
  LoginLazyRoute: typeof LoginLazyRoute
  StudentLazyRoute: typeof StudentLazyRouteWithChildren
  OnboardingTeamLazyRoute: typeof OnboardingTeamLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexLazyRouteImport
      parentRoute: typeof StudentLazyRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexLazyRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/student/team': {
      id: '/student/team'
      path: '/team'
      fullPath: '/student/team'
      preLoaderRoute: typeof StudentTeamLazyRouteImport
      parentRoute: typeof StudentLazyRoute
    }
    '/student/project-topic': {
      id: '/student/project-topic'
      path: '/project-topic'
      fullPath: '/student/project-topic'
      preLoaderRoute: typeof StudentProjectTopicLazyRouteImport
      parentRoute: typeof StudentLazyRoute
    }
    '/student/presentation-evaluation': {
      id: '/student/presentation-evaluation'
      path: '/presentation-evaluation'
      fullPath: '/student/presentation-evaluation'
      preLoaderRoute: typeof StudentPresentationEvaluationLazyRouteImport
      parentRoute: typeof StudentLazyRoute
    }
    '/student/peer-review': {
      id: '/student/peer-review'
      path: '/peer-review'
      fullPath: '/student/peer-review'
      preLoaderRoute: typeof StudentPeerReviewLazyRouteImport
      parentRoute: typeof StudentLazyRoute
    }
    '/student/grades': {
      id: '/student/grades'
      path: '/grades'
      fullPath: '/student/grades'
      preLoaderRoute: typeof StudentGradesLazyRouteImport
      parentRoute: typeof StudentLazyRoute
    }
    '/student/feedback': {
      id: '/student/feedback'
      path: '/feedback'
      fullPath: '/student/feedback'
      preLoaderRoute: typeof StudentFeedbackLazyRouteImport
      parentRoute: typeof StudentLazyRoute
    }
    '/onboarding/team': {
      id: '/onboarding/team'
      path: '/onboarding/team'
      fullPath: '/onboarding/team'
      preLoaderRoute: typeof OnboardingTeamLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/student-team': {
      id: '/admin/student-team'
      path: '/student-team'
      fullPath: '/admin/student-team'
      preLoaderRoute: typeof AdminStudentTeamLazyRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/admin/notices': {
      id: '/admin/notices'
      path: '/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AdminNoticesLazyRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/onboarding/team/': {
      id: '/onboarding/team/'
      path: '/'
      fullPath: '/onboarding/team/'
      preLoaderRoute: typeof OnboardingTeamIndexLazyRouteImport
      parentRoute: typeof OnboardingTeamLazyRoute
    }
    '/admin/notices/': {
      id: '/admin/notices/'
      path: '/'
      fullPath: '/admin/notices/'
      preLoaderRoute: typeof AdminNoticesIndexLazyRouteImport
      parentRoute: typeof AdminNoticesLazyRoute
    }
    '/onboarding/team/survey': {
      id: '/onboarding/team/survey'
      path: '/survey'
      fullPath: '/onboarding/team/survey'
      preLoaderRoute: typeof OnboardingTeamSurveyLazyRouteImport
      parentRoute: typeof OnboardingTeamLazyRoute
    }
    '/onboarding/team/result': {
      id: '/onboarding/team/result'
      path: '/result'
      fullPath: '/onboarding/team/result'
      preLoaderRoute: typeof OnboardingTeamResultLazyRouteImport
      parentRoute: typeof OnboardingTeamLazyRoute
    }
    '/onboarding/team/first-meeting': {
      id: '/onboarding/team/first-meeting'
      path: '/first-meeting'
      fullPath: '/onboarding/team/first-meeting'
      preLoaderRoute: typeof OnboardingTeamFirstMeetingLazyRouteImport
      parentRoute: typeof OnboardingTeamLazyRoute
    }
    '/admin/notices/new': {
      id: '/admin/notices/new'
      path: '/new'
      fullPath: '/admin/notices/new'
      preLoaderRoute: typeof AdminNoticesNewLazyRouteImport
      parentRoute: typeof AdminNoticesLazyRoute
    }
    '/admin/notices/$noticeId': {
      id: '/admin/notices/$noticeId'
      path: '/$noticeId'
      fullPath: '/admin/notices/$noticeId'
      preLoaderRoute: typeof AdminNoticesNoticeIdLazyRouteImport
      parentRoute: typeof AdminNoticesLazyRoute
    }
    '/admin/notices/$noticeId/': {
      id: '/admin/notices/$noticeId/'
      path: '/'
      fullPath: '/admin/notices/$noticeId/'
      preLoaderRoute: typeof AdminNoticesNoticeIdIndexLazyRouteImport
      parentRoute: typeof AdminNoticesNoticeIdLazyRoute
    }
    '/student/editor/proposal/$section': {
      id: '/student/editor/proposal/$section'
      path: '/editor/proposal/$section'
      fullPath: '/student/editor/proposal/$section'
      preLoaderRoute: typeof StudentEditorProposalSectionLazyRouteImport
      parentRoute: typeof StudentLazyRoute
    }
    '/student/editor/presentation/$section': {
      id: '/student/editor/presentation/$section'
      path: '/editor/presentation/$section'
      fullPath: '/student/editor/presentation/$section'
      preLoaderRoute: typeof StudentEditorPresentationSectionLazyRouteImport
      parentRoute: typeof StudentLazyRoute
    }
    '/student/editor/mid-review/$section': {
      id: '/student/editor/mid-review/$section'
      path: '/editor/mid-review/$section'
      fullPath: '/student/editor/mid-review/$section'
      preLoaderRoute: typeof StudentEditorMidReviewSectionLazyRouteImport
      parentRoute: typeof StudentLazyRoute
    }
    '/admin/notices/$noticeId/edit': {
      id: '/admin/notices/$noticeId/edit'
      path: '/edit'
      fullPath: '/admin/notices/$noticeId/edit'
      preLoaderRoute: typeof AdminNoticesNoticeIdEditLazyRouteImport
      parentRoute: typeof AdminNoticesNoticeIdLazyRoute
    }
  }
}

interface AdminNoticesNoticeIdLazyRouteChildren {
  AdminNoticesNoticeIdEditLazyRoute: typeof AdminNoticesNoticeIdEditLazyRoute
  AdminNoticesNoticeIdIndexLazyRoute: typeof AdminNoticesNoticeIdIndexLazyRoute
}

const AdminNoticesNoticeIdLazyRouteChildren: AdminNoticesNoticeIdLazyRouteChildren =
  {
    AdminNoticesNoticeIdEditLazyRoute: AdminNoticesNoticeIdEditLazyRoute,
    AdminNoticesNoticeIdIndexLazyRoute: AdminNoticesNoticeIdIndexLazyRoute,
  }

const AdminNoticesNoticeIdLazyRouteWithChildren =
  AdminNoticesNoticeIdLazyRoute._addFileChildren(
    AdminNoticesNoticeIdLazyRouteChildren,
  )

interface AdminNoticesLazyRouteChildren {
  AdminNoticesNoticeIdLazyRoute: typeof AdminNoticesNoticeIdLazyRouteWithChildren
  AdminNoticesNewLazyRoute: typeof AdminNoticesNewLazyRoute
  AdminNoticesIndexLazyRoute: typeof AdminNoticesIndexLazyRoute
}

const AdminNoticesLazyRouteChildren: AdminNoticesLazyRouteChildren = {
  AdminNoticesNoticeIdLazyRoute: AdminNoticesNoticeIdLazyRouteWithChildren,
  AdminNoticesNewLazyRoute: AdminNoticesNewLazyRoute,
  AdminNoticesIndexLazyRoute: AdminNoticesIndexLazyRoute,
}

const AdminNoticesLazyRouteWithChildren =
  AdminNoticesLazyRoute._addFileChildren(AdminNoticesLazyRouteChildren)

interface AdminLazyRouteChildren {
  AdminNoticesLazyRoute: typeof AdminNoticesLazyRouteWithChildren
  AdminStudentTeamLazyRoute: typeof AdminStudentTeamLazyRoute
  AdminIndexLazyRoute: typeof AdminIndexLazyRoute
}

const AdminLazyRouteChildren: AdminLazyRouteChildren = {
  AdminNoticesLazyRoute: AdminNoticesLazyRouteWithChildren,
  AdminStudentTeamLazyRoute: AdminStudentTeamLazyRoute,
  AdminIndexLazyRoute: AdminIndexLazyRoute,
}

const AdminLazyRouteWithChildren = AdminLazyRoute._addFileChildren(
  AdminLazyRouteChildren,
)

interface StudentLazyRouteChildren {
  StudentFeedbackLazyRoute: typeof StudentFeedbackLazyRoute
  StudentGradesLazyRoute: typeof StudentGradesLazyRoute
  StudentPeerReviewLazyRoute: typeof StudentPeerReviewLazyRoute
  StudentPresentationEvaluationLazyRoute: typeof StudentPresentationEvaluationLazyRoute
  StudentProjectTopicLazyRoute: typeof StudentProjectTopicLazyRoute
  StudentTeamLazyRoute: typeof StudentTeamLazyRoute
  StudentIndexLazyRoute: typeof StudentIndexLazyRoute
  StudentEditorMidReviewSectionLazyRoute: typeof StudentEditorMidReviewSectionLazyRoute
  StudentEditorPresentationSectionLazyRoute: typeof StudentEditorPresentationSectionLazyRoute
  StudentEditorProposalSectionLazyRoute: typeof StudentEditorProposalSectionLazyRoute
}

const StudentLazyRouteChildren: StudentLazyRouteChildren = {
  StudentFeedbackLazyRoute: StudentFeedbackLazyRoute,
  StudentGradesLazyRoute: StudentGradesLazyRoute,
  StudentPeerReviewLazyRoute: StudentPeerReviewLazyRoute,
  StudentPresentationEvaluationLazyRoute:
    StudentPresentationEvaluationLazyRoute,
  StudentProjectTopicLazyRoute: StudentProjectTopicLazyRoute,
  StudentTeamLazyRoute: StudentTeamLazyRoute,
  StudentIndexLazyRoute: StudentIndexLazyRoute,
  StudentEditorMidReviewSectionLazyRoute:
    StudentEditorMidReviewSectionLazyRoute,
  StudentEditorPresentationSectionLazyRoute:
    StudentEditorPresentationSectionLazyRoute,
  StudentEditorProposalSectionLazyRoute: StudentEditorProposalSectionLazyRoute,
}

const StudentLazyRouteWithChildren = StudentLazyRoute._addFileChildren(
  StudentLazyRouteChildren,
)

interface OnboardingTeamLazyRouteChildren {
  OnboardingTeamFirstMeetingLazyRoute: typeof OnboardingTeamFirstMeetingLazyRoute
  OnboardingTeamResultLazyRoute: typeof OnboardingTeamResultLazyRoute
  OnboardingTeamSurveyLazyRoute: typeof OnboardingTeamSurveyLazyRoute
  OnboardingTeamIndexLazyRoute: typeof OnboardingTeamIndexLazyRoute
}

const OnboardingTeamLazyRouteChildren: OnboardingTeamLazyRouteChildren = {
  OnboardingTeamFirstMeetingLazyRoute: OnboardingTeamFirstMeetingLazyRoute,
  OnboardingTeamResultLazyRoute: OnboardingTeamResultLazyRoute,
  OnboardingTeamSurveyLazyRoute: OnboardingTeamSurveyLazyRoute,
  OnboardingTeamIndexLazyRoute: OnboardingTeamIndexLazyRoute,
}

const OnboardingTeamLazyRouteWithChildren =
  OnboardingTeamLazyRoute._addFileChildren(OnboardingTeamLazyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AdminLazyRoute: AdminLazyRouteWithChildren,
  LoginLazyRoute: LoginLazyRoute,
  StudentLazyRoute: StudentLazyRouteWithChildren,
  OnboardingTeamLazyRoute: OnboardingTeamLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
