/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const StudentLazyRouteImport = createFileRoute('/student')()
const LoginLazyRouteImport = createFileRoute('/login')()
const IndexLazyRouteImport = createFileRoute('/')()
const StudentIndexLazyRouteImport = createFileRoute('/student/')()
const StudentTeamLazyRouteImport = createFileRoute('/student/team')()
const StudentSubmissionsLazyRouteImport = createFileRoute(
  '/student/submissions',
)()
const StudentProjectTopicLazyRouteImport = createFileRoute(
  '/student/project-topic',
)()
const StudentPeerReviewLazyRouteImport = createFileRoute(
  '/student/peer-review',
)()
const StudentMilestonesLazyRouteImport = createFileRoute(
  '/student/milestones',
)()
const StudentGradesLazyRouteImport = createFileRoute('/student/grades')()
const StudentFeedbackLazyRouteImport = createFileRoute('/student/feedback')()
const OnboardingTeamLazyRouteImport = createFileRoute('/onboarding/team')()
const OnboardingTeamIndexLazyRouteImport =
  createFileRoute('/onboarding/team/')()
const OnboardingTeamSurveyLazyRouteImport = createFileRoute(
  '/onboarding/team/survey',
)()
const OnboardingTeamResultLazyRouteImport = createFileRoute(
  '/onboarding/team/result',
)()
const OnboardingTeamFirstMeetingLazyRouteImport = createFileRoute(
  '/onboarding/team/first-meeting',
)()

const StudentLazyRoute = StudentLazyRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/student.lazy').then((d) => d.Route))
const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const StudentIndexLazyRoute = StudentIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentLazyRoute,
} as any).lazy(() => import('./routes/student.index.lazy').then((d) => d.Route))
const StudentTeamLazyRoute = StudentTeamLazyRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => StudentLazyRoute,
} as any).lazy(() => import('./routes/student.team.lazy').then((d) => d.Route))
const StudentSubmissionsLazyRoute = StudentSubmissionsLazyRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => StudentLazyRoute,
} as any).lazy(() =>
  import('./routes/student.submissions.lazy').then((d) => d.Route),
)
const StudentProjectTopicLazyRoute = StudentProjectTopicLazyRouteImport.update({
  id: '/project-topic',
  path: '/project-topic',
  getParentRoute: () => StudentLazyRoute,
} as any).lazy(() =>
  import('./routes/student.project-topic.lazy').then((d) => d.Route),
)
const StudentPeerReviewLazyRoute = StudentPeerReviewLazyRouteImport.update({
  id: '/peer-review',
  path: '/peer-review',
  getParentRoute: () => StudentLazyRoute,
} as any).lazy(() =>
  import('./routes/student.peer-review.lazy').then((d) => d.Route),
)
const StudentMilestonesLazyRoute = StudentMilestonesLazyRouteImport.update({
  id: '/milestones',
  path: '/milestones',
  getParentRoute: () => StudentLazyRoute,
} as any).lazy(() =>
  import('./routes/student.milestones.lazy').then((d) => d.Route),
)
const StudentGradesLazyRoute = StudentGradesLazyRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => StudentLazyRoute,
} as any).lazy(() =>
  import('./routes/student.grades.lazy').then((d) => d.Route),
)
const StudentFeedbackLazyRoute = StudentFeedbackLazyRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => StudentLazyRoute,
} as any).lazy(() =>
  import('./routes/student.feedback.lazy').then((d) => d.Route),
)
const OnboardingTeamLazyRoute = OnboardingTeamLazyRouteImport.update({
  id: '/onboarding/team',
  path: '/onboarding/team',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/onboarding.team.lazy').then((d) => d.Route),
)
const OnboardingTeamIndexLazyRoute = OnboardingTeamIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingTeamLazyRoute,
} as any).lazy(() =>
  import('./routes/onboarding.team.index.lazy').then((d) => d.Route),
)
const OnboardingTeamSurveyLazyRoute =
  OnboardingTeamSurveyLazyRouteImport.update({
    id: '/survey',
    path: '/survey',
    getParentRoute: () => OnboardingTeamLazyRoute,
  } as any).lazy(() =>
    import('./routes/onboarding.team.survey.lazy').then((d) => d.Route),
  )
const OnboardingTeamResultLazyRoute =
  OnboardingTeamResultLazyRouteImport.update({
    id: '/result',
    path: '/result',
    getParentRoute: () => OnboardingTeamLazyRoute,
  } as any).lazy(() =>
    import('./routes/onboarding.team.result.lazy').then((d) => d.Route),
  )
const OnboardingTeamFirstMeetingLazyRoute =
  OnboardingTeamFirstMeetingLazyRouteImport.update({
    id: '/first-meeting',
    path: '/first-meeting',
    getParentRoute: () => OnboardingTeamLazyRoute,
  } as any).lazy(() =>
    import('./routes/onboarding.team.first-meeting.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/login': typeof LoginLazyRoute
  '/student': typeof StudentLazyRouteWithChildren
  '/onboarding/team': typeof OnboardingTeamLazyRouteWithChildren
  '/student/feedback': typeof StudentFeedbackLazyRoute
  '/student/grades': typeof StudentGradesLazyRoute
  '/student/milestones': typeof StudentMilestonesLazyRoute
  '/student/peer-review': typeof StudentPeerReviewLazyRoute
  '/student/project-topic': typeof StudentProjectTopicLazyRoute
  '/student/submissions': typeof StudentSubmissionsLazyRoute
  '/student/team': typeof StudentTeamLazyRoute
  '/student/': typeof StudentIndexLazyRoute
  '/onboarding/team/first-meeting': typeof OnboardingTeamFirstMeetingLazyRoute
  '/onboarding/team/result': typeof OnboardingTeamResultLazyRoute
  '/onboarding/team/survey': typeof OnboardingTeamSurveyLazyRoute
  '/onboarding/team/': typeof OnboardingTeamIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/login': typeof LoginLazyRoute
  '/student/feedback': typeof StudentFeedbackLazyRoute
  '/student/grades': typeof StudentGradesLazyRoute
  '/student/milestones': typeof StudentMilestonesLazyRoute
  '/student/peer-review': typeof StudentPeerReviewLazyRoute
  '/student/project-topic': typeof StudentProjectTopicLazyRoute
  '/student/submissions': typeof StudentSubmissionsLazyRoute
  '/student/team': typeof StudentTeamLazyRoute
  '/student': typeof StudentIndexLazyRoute
  '/onboarding/team/first-meeting': typeof OnboardingTeamFirstMeetingLazyRoute
  '/onboarding/team/result': typeof OnboardingTeamResultLazyRoute
  '/onboarding/team/survey': typeof OnboardingTeamSurveyLazyRoute
  '/onboarding/team': typeof OnboardingTeamIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/login': typeof LoginLazyRoute
  '/student': typeof StudentLazyRouteWithChildren
  '/onboarding/team': typeof OnboardingTeamLazyRouteWithChildren
  '/student/feedback': typeof StudentFeedbackLazyRoute
  '/student/grades': typeof StudentGradesLazyRoute
  '/student/milestones': typeof StudentMilestonesLazyRoute
  '/student/peer-review': typeof StudentPeerReviewLazyRoute
  '/student/project-topic': typeof StudentProjectTopicLazyRoute
  '/student/submissions': typeof StudentSubmissionsLazyRoute
  '/student/team': typeof StudentTeamLazyRoute
  '/student/': typeof StudentIndexLazyRoute
  '/onboarding/team/first-meeting': typeof OnboardingTeamFirstMeetingLazyRoute
  '/onboarding/team/result': typeof OnboardingTeamResultLazyRoute
  '/onboarding/team/survey': typeof OnboardingTeamSurveyLazyRoute
  '/onboarding/team/': typeof OnboardingTeamIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/student'
    | '/onboarding/team'
    | '/student/feedback'
    | '/student/grades'
    | '/student/milestones'
    | '/student/peer-review'
    | '/student/project-topic'
    | '/student/submissions'
    | '/student/team'
    | '/student/'
    | '/onboarding/team/first-meeting'
    | '/onboarding/team/result'
    | '/onboarding/team/survey'
    | '/onboarding/team/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/student/feedback'
    | '/student/grades'
    | '/student/milestones'
    | '/student/peer-review'
    | '/student/project-topic'
    | '/student/submissions'
    | '/student/team'
    | '/student'
    | '/onboarding/team/first-meeting'
    | '/onboarding/team/result'
    | '/onboarding/team/survey'
    | '/onboarding/team'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/student'
    | '/onboarding/team'
    | '/student/feedback'
    | '/student/grades'
    | '/student/milestones'
    | '/student/peer-review'
    | '/student/project-topic'
    | '/student/submissions'
    | '/student/team'
    | '/student/'
    | '/onboarding/team/first-meeting'
    | '/onboarding/team/result'
    | '/onboarding/team/survey'
    | '/onboarding/team/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  StudentLazyRoute: typeof StudentLazyRouteWithChildren
  OnboardingTeamLazyRoute: typeof OnboardingTeamLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexLazyRouteImport
      parentRoute: typeof StudentLazyRoute
    }
    '/student/team': {
      id: '/student/team'
      path: '/team'
      fullPath: '/student/team'
      preLoaderRoute: typeof StudentTeamLazyRouteImport
      parentRoute: typeof StudentLazyRoute
    }
    '/student/submissions': {
      id: '/student/submissions'
      path: '/submissions'
      fullPath: '/student/submissions'
      preLoaderRoute: typeof StudentSubmissionsLazyRouteImport
      parentRoute: typeof StudentLazyRoute
    }
    '/student/project-topic': {
      id: '/student/project-topic'
      path: '/project-topic'
      fullPath: '/student/project-topic'
      preLoaderRoute: typeof StudentProjectTopicLazyRouteImport
      parentRoute: typeof StudentLazyRoute
    }
    '/student/peer-review': {
      id: '/student/peer-review'
      path: '/peer-review'
      fullPath: '/student/peer-review'
      preLoaderRoute: typeof StudentPeerReviewLazyRouteImport
      parentRoute: typeof StudentLazyRoute
    }
    '/student/milestones': {
      id: '/student/milestones'
      path: '/milestones'
      fullPath: '/student/milestones'
      preLoaderRoute: typeof StudentMilestonesLazyRouteImport
      parentRoute: typeof StudentLazyRoute
    }
    '/student/grades': {
      id: '/student/grades'
      path: '/grades'
      fullPath: '/student/grades'
      preLoaderRoute: typeof StudentGradesLazyRouteImport
      parentRoute: typeof StudentLazyRoute
    }
    '/student/feedback': {
      id: '/student/feedback'
      path: '/feedback'
      fullPath: '/student/feedback'
      preLoaderRoute: typeof StudentFeedbackLazyRouteImport
      parentRoute: typeof StudentLazyRoute
    }
    '/onboarding/team': {
      id: '/onboarding/team'
      path: '/onboarding/team'
      fullPath: '/onboarding/team'
      preLoaderRoute: typeof OnboardingTeamLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/team/': {
      id: '/onboarding/team/'
      path: '/'
      fullPath: '/onboarding/team/'
      preLoaderRoute: typeof OnboardingTeamIndexLazyRouteImport
      parentRoute: typeof OnboardingTeamLazyRoute
    }
    '/onboarding/team/survey': {
      id: '/onboarding/team/survey'
      path: '/survey'
      fullPath: '/onboarding/team/survey'
      preLoaderRoute: typeof OnboardingTeamSurveyLazyRouteImport
      parentRoute: typeof OnboardingTeamLazyRoute
    }
    '/onboarding/team/result': {
      id: '/onboarding/team/result'
      path: '/result'
      fullPath: '/onboarding/team/result'
      preLoaderRoute: typeof OnboardingTeamResultLazyRouteImport
      parentRoute: typeof OnboardingTeamLazyRoute
    }
    '/onboarding/team/first-meeting': {
      id: '/onboarding/team/first-meeting'
      path: '/first-meeting'
      fullPath: '/onboarding/team/first-meeting'
      preLoaderRoute: typeof OnboardingTeamFirstMeetingLazyRouteImport
      parentRoute: typeof OnboardingTeamLazyRoute
    }
  }
}

interface StudentLazyRouteChildren {
  StudentFeedbackLazyRoute: typeof StudentFeedbackLazyRoute
  StudentGradesLazyRoute: typeof StudentGradesLazyRoute
  StudentMilestonesLazyRoute: typeof StudentMilestonesLazyRoute
  StudentPeerReviewLazyRoute: typeof StudentPeerReviewLazyRoute
  StudentProjectTopicLazyRoute: typeof StudentProjectTopicLazyRoute
  StudentSubmissionsLazyRoute: typeof StudentSubmissionsLazyRoute
  StudentTeamLazyRoute: typeof StudentTeamLazyRoute
  StudentIndexLazyRoute: typeof StudentIndexLazyRoute
}

const StudentLazyRouteChildren: StudentLazyRouteChildren = {
  StudentFeedbackLazyRoute: StudentFeedbackLazyRoute,
  StudentGradesLazyRoute: StudentGradesLazyRoute,
  StudentMilestonesLazyRoute: StudentMilestonesLazyRoute,
  StudentPeerReviewLazyRoute: StudentPeerReviewLazyRoute,
  StudentProjectTopicLazyRoute: StudentProjectTopicLazyRoute,
  StudentSubmissionsLazyRoute: StudentSubmissionsLazyRoute,
  StudentTeamLazyRoute: StudentTeamLazyRoute,
  StudentIndexLazyRoute: StudentIndexLazyRoute,
}

const StudentLazyRouteWithChildren = StudentLazyRoute._addFileChildren(
  StudentLazyRouteChildren,
)

interface OnboardingTeamLazyRouteChildren {
  OnboardingTeamFirstMeetingLazyRoute: typeof OnboardingTeamFirstMeetingLazyRoute
  OnboardingTeamResultLazyRoute: typeof OnboardingTeamResultLazyRoute
  OnboardingTeamSurveyLazyRoute: typeof OnboardingTeamSurveyLazyRoute
  OnboardingTeamIndexLazyRoute: typeof OnboardingTeamIndexLazyRoute
}

const OnboardingTeamLazyRouteChildren: OnboardingTeamLazyRouteChildren = {
  OnboardingTeamFirstMeetingLazyRoute: OnboardingTeamFirstMeetingLazyRoute,
  OnboardingTeamResultLazyRoute: OnboardingTeamResultLazyRoute,
  OnboardingTeamSurveyLazyRoute: OnboardingTeamSurveyLazyRoute,
  OnboardingTeamIndexLazyRoute: OnboardingTeamIndexLazyRoute,
}

const OnboardingTeamLazyRouteWithChildren =
  OnboardingTeamLazyRoute._addFileChildren(OnboardingTeamLazyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  StudentLazyRoute: StudentLazyRouteWithChildren,
  OnboardingTeamLazyRoute: OnboardingTeamLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
